"""empty message

Revision ID: 8078be0b1088
Revises: e27fe1ac4050
Create Date: 2020-02-26 22:00:24.137530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8078be0b1088'
down_revision = 'e27fe1ac4050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atifical_ai',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('articalName', sa.String(), nullable=False),
    sa.Column('writtenDate', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('autherCode', sa.String(), nullable=False),
    sa.Column('autherName', sa.String(), nullable=False),
    sa.Column('articalCode', sa.String(), nullable=False),
    sa.Column('isResereved', sa.String(), nullable=False),
    sa.Column('reserevedBy', sa.String(), nullable=False),
    sa.Column('publishDate', sa.DateTime(), nullable=False),
    sa.Column('publishingHouse', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('articalCode'),
    sa.UniqueConstraint('autherCode')
    )
    op.create_table('cron_job_ai',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('jobName', sa.String(), nullable=False),
    sa.Column('JobCode', sa.String(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('cronExpression', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('JobCode')
    )
    op.create_table('cron_job_info',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('jobName', sa.String(), nullable=False),
    sa.Column('JobCode', sa.String(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('cronExpression', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('JobCode')
    )
    op.create_table('cron_job_lookup',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('lookupKey', sa.String(), nullable=False),
    sa.Column('lookupValue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cron_job_lookup_ai',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('lookupKey', sa.String(), nullable=False),
    sa.Column('lookupValue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fetch_api_info',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('newsName', sa.String(), nullable=False),
    sa.Column('newsTitle', sa.String(), nullable=False),
    sa.Column('newsText', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('newsTitle')
    )
    op.create_table('history_info',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('newsName', sa.String(), nullable=False),
    sa.Column('newsTitle', sa.String(), nullable=False),
    sa.Column('newsText', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('newsTitle')
    )
    op.create_table('history_lookup',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('lookupKey', sa.String(), nullable=False),
    sa.Column('lookupValue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_info',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('imageName', sa.String(), nullable=False),
    sa.Column('imageTitle', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imageTitle')
    )
    op.create_table('jwt_token_permit',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('permitCode', sa.String(), nullable=False),
    sa.Column('permitName', sa.String(), nullable=False),
    sa.Column('permitKey', sa.String(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jwt_token_signature',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('signatureName', sa.String(), nullable=False),
    sa.Column('signCode', sa.String(), nullable=False),
    sa.Column('signKey', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signCode')
    )
    op.create_table('jwt_token_signature_lookup',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('lookupKey', sa.String(), nullable=False),
    sa.Column('lookupValue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jwt_token_transaction',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('tansactionCode', sa.String(), nullable=False),
    sa.Column('tansactionKey', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tansactionKey')
    )
    op.create_table('jwt_user_history',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('jwtName', sa.String(), nullable=False),
    sa.Column('jwtCode', sa.String(), nullable=False),
    sa.Column('jwtKey', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jwtCode')
    )
    op.create_table('keyword_info',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('keywork', sa.String(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_lookup',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('lookupKey', sa.String(), nullable=False),
    sa.Column('lookupValue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations_based_role',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('operationName', sa.String(), nullable=False),
    sa.Column('createDate', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('userCode', sa.String(), nullable=False),
    sa.Column('userName', sa.String(), nullable=False),
    sa.Column('operationCode', sa.String(), nullable=False),
    sa.Column('isResereved', sa.String(), nullable=False),
    sa.Column('reserevedBy', sa.String(), nullable=False),
    sa.Column('isAllow', sa.Boolean(), nullable=False),
    sa.Column('isPermit', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operationCode'),
    sa.UniqueConstraint('userCode')
    )
    op.create_table('select_info',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('articalName', sa.String(), nullable=False),
    sa.Column('writtenDate', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('autherCode', sa.String(), nullable=False),
    sa.Column('autherName', sa.String(), nullable=False),
    sa.Column('articalCode', sa.String(), nullable=False),
    sa.Column('isResereved', sa.String(), nullable=False),
    sa.Column('reserevedBy', sa.String(), nullable=False),
    sa.Column('publishDate', sa.DateTime(), nullable=False),
    sa.Column('publishingHouse', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('articalCode'),
    sa.UniqueConstraint('autherCode')
    )
    op.create_table('subject_info',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('keywork', sa.String(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_jwt_cron_jobs',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('jobName', sa.String(), nullable=False),
    sa.Column('JobCode', sa.String(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('cronExpression', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('JobCode')
    )
    op.create_table('token_jwt_expire',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('jwtCode', sa.String(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_jwt_expire_lookup',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('keywork', sa.String(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_lookup',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('lookupKey', sa.String(), nullable=False),
    sa.Column('lookupValue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_info',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('keywork', sa.String(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_history_info',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('articalName', sa.String(), nullable=False),
    sa.Column('writtenDate', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('autherCode', sa.String(), nullable=False),
    sa.Column('autherName', sa.String(), nullable=False),
    sa.Column('articalCode', sa.String(), nullable=False),
    sa.Column('isResereved', sa.String(), nullable=False),
    sa.Column('reserevedBy', sa.String(), nullable=False),
    sa.Column('publishDate', sa.DateTime(), nullable=False),
    sa.Column('publishingHouse', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('articalCode'),
    sa.UniqueConstraint('autherCode')
    )
    op.create_table('transaction_history_token',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('jwtCode', sa.String(), nullable=False),
    sa.Column('jwtDate', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('jwtName', sa.String(), nullable=False),
    sa.Column('jwtKey', sa.String(), nullable=False),
    sa.Column('jwtOperationName', sa.String(), nullable=False),
    sa.Column('isResereved', sa.String(), nullable=False),
    sa.Column('reserevedBy', sa.String(), nullable=False),
    sa.Column('operationCode', sa.DateTime(), nullable=False),
    sa.Column('operationGuid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jwtName'),
    sa.UniqueConstraint('jwtOperationName')
    )
    op.create_table('transaction_lookup',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('lookupKey', sa.String(), nullable=False),
    sa.Column('lookupValue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_info',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('urlLink', sa.String(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_info_ai',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('urlLink', sa.String(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_patterns_auth',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.Column('urlLink', sa.String(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('isExpired', sa.Boolean(), nullable=False),
    sa.Column('controller', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_tokens_auths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tokens_auths')
    op.drop_table('user')
    op.drop_table('url_patterns_auth')
    op.drop_table('url_info_ai')
    op.drop_table('url_info')
    op.drop_table('transaction_lookup')
    op.drop_table('transaction_history_token')
    op.drop_table('transaction_history_info')
    op.drop_table('topic_info')
    op.drop_table('token_lookup')
    op.drop_table('token_jwt_expire_lookup')
    op.drop_table('token_jwt_expire')
    op.drop_table('token_jwt_cron_jobs')
    op.drop_table('subject_info')
    op.drop_table('select_info')
    op.drop_table('operations_based_role')
    op.drop_table('news_lookup')
    op.drop_table('keyword_info')
    op.drop_table('jwt_user_history')
    op.drop_table('jwt_token_transaction')
    op.drop_table('jwt_token_signature_lookup')
    op.drop_table('jwt_token_signature')
    op.drop_table('jwt_token_permit')
    op.drop_table('image_info')
    op.drop_table('history_lookup')
    op.drop_table('history_info')
    op.drop_table('fetch_api_info')
    op.drop_table('cron_job_lookup_ai')
    op.drop_table('cron_job_lookup')
    op.drop_table('cron_job_info')
    op.drop_table('cron_job_ai')
    op.drop_table('atifical_ai')
    # ### end Alembic commands ###
